CREATE TABLE [dbo].[User]
(
	[UserID] INT IDENTITY,
    [FirstName] NVARCHAR(50) NOT NULL,
    [LastName] NVARCHAR(50) NOT NULL,
    [Email] NVARCHAR(50) NOT NULL, 
    [Salt] NVARCHAR NOT NULL,
    [PasswordHash] VARBINARY(64) NOT NULL,
    CONSTRAINT [PK_User] PRIMARY KEY (UserID),
    UNIQUE NONCLUSTERED ([Email] ASC)

)
